var getCountryAbb = function() {
    var countryAbbreviationTable = new HashMap();
	
    countryAbbreviationTable.put("Afghanistan", "AFG");
    countryAbbreviationTable.put("Albania", "ALB");
    countryAbbreviationTable.put("Algeria", "DZA");
    countryAbbreviationTable.put("American Samoa", "ASM");
    countryAbbreviationTable.put("Andorra", "AND");
    countryAbbreviationTable.put("Angola", "AGO");
    countryAbbreviationTable.put("Anguilla", "AIA");
    countryAbbreviationTable.put("Antarctica", "ATA");
    countryAbbreviationTable.put("Antigua and Barbuda", "ATG");
    countryAbbreviationTable.put("Argentina", "ARG");
    countryAbbreviationTable.put("Armenia", "ARM");
    countryAbbreviationTable.put("Aruba", "ABW");
    countryAbbreviationTable.put("Australia", "AUS");
    countryAbbreviationTable.put("Austria", "AUT");
    countryAbbreviationTable.put("Azerbaijan", "AZE");
    countryAbbreviationTable.put("Bahamas", "BHS");
    countryAbbreviationTable.put("Bahrain", "BHR");
    countryAbbreviationTable.put("Bangladesh", "BGD");
    countryAbbreviationTable.put("Barbados", "BRB");
    countryAbbreviationTable.put("Belarus", "BLR");
    countryAbbreviationTable.put("Belgium", "BEL");
    countryAbbreviationTable.put("Belize", "BLZ");
    countryAbbreviationTable.put("Benin", "BEN");
    countryAbbreviationTable.put("Bermuda", "BMU");
    countryAbbreviationTable.put("Bhutan", "BTN");
    countryAbbreviationTable.put("Bolivia", "BOL");
    countryAbbreviationTable.put("Bosnia Herzegovina", "BIH");
    countryAbbreviationTable.put("Botswana", "BWA");
    countryAbbreviationTable.put("Bouvet Island", "BVT");
    countryAbbreviationTable.put("Brazil", "BRA");
    countryAbbreviationTable.put("British Indian Ocean Territory", "IOT");
    countryAbbreviationTable.put("Brunei", "BRN");
    countryAbbreviationTable.put("Bulgaria", "BGR");
    countryAbbreviationTable.put("Burkina Faso", "BFA");
    countryAbbreviationTable.put("Burundi", "BDI");
    countryAbbreviationTable.put("Cambodia", "KHM");
    countryAbbreviationTable.put("Cameroon", "CMR");
    countryAbbreviationTable.put("Canada", "CAN");
    countryAbbreviationTable.put("Cape Verde", "CPV");
    countryAbbreviationTable.put("Cayman Islands", "CYM");
    countryAbbreviationTable.put("Central African Republic", "CAF");
    countryAbbreviationTable.put("Chad", "TCD");
    countryAbbreviationTable.put("Chile", "CHL");
    countryAbbreviationTable.put("China", "CHN");
    countryAbbreviationTable.put("Colombia", "COL");
    countryAbbreviationTable.put("Comoros", "COM");
    countryAbbreviationTable.put("Congo (Democratic Republic)", "COD");
    countryAbbreviationTable.put("Congo (Republic)", "COG");
    countryAbbreviationTable.put("Cook Islands", "COK");
    countryAbbreviationTable.put("Costa Rica", "CRI");
    countryAbbreviationTable.put("Cote d'Ivoire", "CIV");
    countryAbbreviationTable.put("Croatia", "HRV");
    countryAbbreviationTable.put("Cuba", "CUB");
    countryAbbreviationTable.put("Cyprus", "CYP");
    countryAbbreviationTable.put("Czech Republic", "CZE");
    countryAbbreviationTable.put("Denmark", "DNK");
    countryAbbreviationTable.put("Djibouti", "DJI");
    countryAbbreviationTable.put("Dominica", "DMA");
    countryAbbreviationTable.put("Dominican Republic", "DOM");
    countryAbbreviationTable.put("East Timor", "TMP");
    countryAbbreviationTable.put("Ecuador", "ECU");
    countryAbbreviationTable.put("Egypt", "EGY");
    countryAbbreviationTable.put("El Salvador", "SLV");
    countryAbbreviationTable.put("Equatorial Guinea", "GNQ");
    countryAbbreviationTable.put("Eritrea", "ERI");
    countryAbbreviationTable.put("Estonia", "EST");
    countryAbbreviationTable.put("Ethiopia", "ETH");
    countryAbbreviationTable.put("European Union", "EUN");
    countryAbbreviationTable.put("Falkland Islands (Malvinas)", "FNK");
    countryAbbreviationTable.put("Faroe Islands", "FRO");
    countryAbbreviationTable.put("Fiji", "FJI");
    countryAbbreviationTable.put("Finland", "FIN");
    countryAbbreviationTable.put("France", "FRA");
    countryAbbreviationTable.put("France, Metropolitan", "FXX");
    countryAbbreviationTable.put("French Guiana", "GUF");
    countryAbbreviationTable.put("French Polynesia", "PYF");
    countryAbbreviationTable.put("French Southern Territories", "ATF");
    countryAbbreviationTable.put("Gabon", "GAB");
    countryAbbreviationTable.put("Gambia", "GMB");
    countryAbbreviationTable.put("Georgia", "GEO");
    countryAbbreviationTable.put("Germany", "DEU");
    countryAbbreviationTable.put("Ghana", "GHA");
    countryAbbreviationTable.put("Gibraltar", "GIB");
    countryAbbreviationTable.put("Greece", "GRC");
    countryAbbreviationTable.put("Greenland", "GRL");
    countryAbbreviationTable.put("Grenada", "GRD");
    countryAbbreviationTable.put("Guadeloupe", "GLP");
    countryAbbreviationTable.put("Guam", "GUM");
    countryAbbreviationTable.put("Guatemala", "GTM");
    countryAbbreviationTable.put("Guinea", "GIN");
    countryAbbreviationTable.put("Guinea-Bissau", "GNB");
    countryAbbreviationTable.put("Guyana", "GUY");
    countryAbbreviationTable.put("Haiti", "HTI");
    countryAbbreviationTable.put("Heard and Mc Donald Islands", "HMD");
    countryAbbreviationTable.put("Holy See (Vatican City State)", "VAT");
    countryAbbreviationTable.put("Honduras", "HND");
    countryAbbreviationTable.put("Hong Kong", "HKG");
    countryAbbreviationTable.put("Hungary", "HUN");
    countryAbbreviationTable.put("Iceland", "ISL");
    countryAbbreviationTable.put("India", "IND");
    countryAbbreviationTable.put("Indonesia", "IDN");
    countryAbbreviationTable.put("Iran", "IRN");
    countryAbbreviationTable.put("Iraq", "IRQ");
    countryAbbreviationTable.put("Ireland", "IRL");
    countryAbbreviationTable.put("Israel", "ISR");
    countryAbbreviationTable.put("Italy", "ITA");
    countryAbbreviationTable.put("Jamaica", "JAM");
    countryAbbreviationTable.put("Japan", "JPN");
    countryAbbreviationTable.put("Jordan", "JOR");
    countryAbbreviationTable.put("Kazakhstan", "KAZ");
    countryAbbreviationTable.put("Kenya", "KEN");
    countryAbbreviationTable.put("Kiribati", "KIR");
    countryAbbreviationTable.put("Korea, D.P.R.O", "PRK");
    countryAbbreviationTable.put("Korea (South)", "KOR");
    countryAbbreviationTable.put("Kosovo", "KOS");
    countryAbbreviationTable.put("Kuwait", "KWT");
    countryAbbreviationTable.put("Kyrgyzstan", "KGZ");
    countryAbbreviationTable.put("Laos", "LAO");
    countryAbbreviationTable.put("Latvia", "LVA");
    countryAbbreviationTable.put("Lebanon", "LBN");
    countryAbbreviationTable.put("Lesotho", "LSO");
    countryAbbreviationTable.put("Liberia", "LBR");
    countryAbbreviationTable.put("Libya", "LBY");
    countryAbbreviationTable.put("Liechtenstein", "LIE");
    countryAbbreviationTable.put("Lithuania", "LTU");
    countryAbbreviationTable.put("Luxembourg", "LUX");
    countryAbbreviationTable.put("Macau", "MAC");
    countryAbbreviationTable.put("Macedonia", "MKD");
    countryAbbreviationTable.put("Madagascar", "MDG");
    countryAbbreviationTable.put("Malawi", "MWI");
    countryAbbreviationTable.put("Malaysia", "MYS");
    countryAbbreviationTable.put("Maldives", "MDV");
    countryAbbreviationTable.put("Mali", "MLI");
    countryAbbreviationTable.put("Malta", "MLT");
    countryAbbreviationTable.put("Marshall Islands", "MHL");
    countryAbbreviationTable.put("Martinique", "MTQ");
    countryAbbreviationTable.put("Mauritania", "MRT");
    countryAbbreviationTable.put("Mauritius", "MUS");
    countryAbbreviationTable.put("Mayotte", "MYT");
    countryAbbreviationTable.put("Mexico", "MEX");
    countryAbbreviationTable.put("Micronesia", "FSM");
    countryAbbreviationTable.put("Moldova", "MDA");
    countryAbbreviationTable.put("Monaco", "MCO");
    countryAbbreviationTable.put("Mongolia", "MNG");
    countryAbbreviationTable.put("Montenegro", "MNE");
    countryAbbreviationTable.put("Montserrat", "MSR");
    countryAbbreviationTable.put("Morocco", "MAR");
    countryAbbreviationTable.put("Mozambique", "MOZ");
    countryAbbreviationTable.put("Myanmar", "MMR");
    countryAbbreviationTable.put("Namibia", "NAM");
    countryAbbreviationTable.put("Nauru", "NRU");
    countryAbbreviationTable.put("Nepal", "NPL");
    countryAbbreviationTable.put("Netherlands", "NLD");
    countryAbbreviationTable.put("Netherlands Antilles", "ANT");
    countryAbbreviationTable.put("New Caledonia", "NCL");
    countryAbbreviationTable.put("New Zealand", "NZL");
    countryAbbreviationTable.put("Nicaragua", "NIC");
    countryAbbreviationTable.put("Niger", "NER");
    countryAbbreviationTable.put("Nigeria", "NGA");
    countryAbbreviationTable.put("Niue", "NIU");
    countryAbbreviationTable.put("Norfolk Island", "NFK");
    countryAbbreviationTable.put("Northern Mariana Islands", "MNP");
    countryAbbreviationTable.put("Norway", "NOR");
    countryAbbreviationTable.put("Oman", "OMN");
    countryAbbreviationTable.put("Pakistan", "PAK");
    countryAbbreviationTable.put("Palau", "PLW");
    countryAbbreviationTable.put("Panama", "PAN");
    countryAbbreviationTable.put("Papua New Guinea", "PNG");
    countryAbbreviationTable.put("Paraguay", "PRY");
    countryAbbreviationTable.put("Peru", "PER");
    countryAbbreviationTable.put("Philippines", "PHL");
    countryAbbreviationTable.put("Poland", "POL");
    countryAbbreviationTable.put("Portugal", "PRT");
    countryAbbreviationTable.put("Puerto Rico", "PRI");
    countryAbbreviationTable.put("Qatar", "QAT");
    countryAbbreviationTable.put("Reunion", "REU");
    countryAbbreviationTable.put("Romania", "ROM");
    countryAbbreviationTable.put("Russia", "RUS");
    countryAbbreviationTable.put("Rwanda", "RWA");
    countryAbbreviationTable.put("St Kitts and Nevis", "KNA");
    countryAbbreviationTable.put("St Lucia", "LCA");
    countryAbbreviationTable.put("Saint Vincent and the Grenadines", "VCT");
    countryAbbreviationTable.put("Samoa", "WSM");
    countryAbbreviationTable.put("San Marino", "SMR");
    countryAbbreviationTable.put("Sao Tome and Principe", "STP");
    countryAbbreviationTable.put("Saudi Arabia", "SAU");
    countryAbbreviationTable.put("Senegal", "SEN");
    countryAbbreviationTable.put("Serbia", "SRB");
    countryAbbreviationTable.put("Serbia and Montenegro", "SRM");
    countryAbbreviationTable.put("Seychelles", "SYC");
    countryAbbreviationTable.put("Sierra Leone", "SLE");
    countryAbbreviationTable.put("Singapore", "SGP");
    countryAbbreviationTable.put("Slovak Republic", "SVK");
    countryAbbreviationTable.put("Slovenia", "SVN");
    countryAbbreviationTable.put("Solomon Islands", "SLB");
    countryAbbreviationTable.put("Somalia", "SOM");
    countryAbbreviationTable.put("South Africa", "ZAF");
    countryAbbreviationTable.put("South Sudan", "SSD");
    countryAbbreviationTable.put("South Georgia and South S.S.", "SGS");
    countryAbbreviationTable.put("Spain", "ESP");
    countryAbbreviationTable.put("Sri Lanka", "LKA");
    countryAbbreviationTable.put("St. Helena", "SHN");
    countryAbbreviationTable.put("St. Pierre and Miquelon", "SPM");
    countryAbbreviationTable.put("Sudan", "SDN");
    countryAbbreviationTable.put("Suriname", "SUR");
    countryAbbreviationTable.put("Svalbard and Jan Mayen Islands", "SJM");
    countryAbbreviationTable.put("Swaziland", "SWZ");
    countryAbbreviationTable.put("Sweden", "SWE");
    countryAbbreviationTable.put("Switzerland", "CHE");
    countryAbbreviationTable.put("Syria", "SYR");
    countryAbbreviationTable.put("Taiwan", "TWN");
    countryAbbreviationTable.put("Tajikistan", "TJK");
    countryAbbreviationTable.put("Tanzania", "TZA");
    countryAbbreviationTable.put("Thailand", "THA");
    countryAbbreviationTable.put("Togo", "TGO");
    countryAbbreviationTable.put("Tokelau", "TKL");
    countryAbbreviationTable.put("Tonga", "TON");
    countryAbbreviationTable.put("Trinidad and Tobago", "TTO");
    countryAbbreviationTable.put("Tunisia", "TUN");
    countryAbbreviationTable.put("Turkey", "TUR");
    countryAbbreviationTable.put("Turkmenistan", "TKM");
    countryAbbreviationTable.put("Turks and Caicos Islands", "TCA");
    countryAbbreviationTable.put("Tuvalu", "TUV");
    countryAbbreviationTable.put("Uganda", "UGA");
    countryAbbreviationTable.put("Ukraine", "UKR");
    countryAbbreviationTable.put("United Arab Emirates", "ARE");
    countryAbbreviationTable.put("United Kingdom", "GBR");
    countryAbbreviationTable.put("United States", "USA");
    countryAbbreviationTable.put("U.S. Minor Islands", "UMI");
    countryAbbreviationTable.put("Uruguay", "URY");
    countryAbbreviationTable.put("Uzbekistan", "UZB");
    countryAbbreviationTable.put("Vanuatu", "VUT");
    countryAbbreviationTable.put("Venezuela", "VEN");
    countryAbbreviationTable.put("Vietnam", "VNM");
    countryAbbreviationTable.put("Yemen", "YEM");
    countryAbbreviationTable.put("Zambia", "ZMB");
    countryAbbreviationTable.put("Zimbabwe", "ZWE");
    
    return countryAbbreviationTable;
};